# This makes Travis CI use the container-based infrastructure which starts
# tests faster.
sudo: false

language: "python"

python:
  - "3.6"

addons:
  apt:
    packages:
    - "enchant"

before_install:
    - "pip install --upgrade pip setuptools"

install:
  - "pip install --upgrade --editable .[dev]"
  - "npm install -g markdownlint-cli"

cache: "pip"

before_script:
    - "make lint"
    - "markdownlint --config .markdownlint.json README.md"
    # Build documentation HTML.
    - "make -C docs clean html"
    # Create an environment file used by `pytest-envfiles`.
    # We don't add to this because we have environment variables set in the CI
    # config.
    - "touch vuforia_secrets.env"
    # We use a different database for `master` builds.
    - "if [ \"$TRAVIS_BRANCH\" = \"master\" -a \"$TRAVIS_PULL_REQUEST\" = \"false\" ]; then
        echo 'Using Vuforia credentials for $MASTER_VUFORIA_TARGET_MANAGER_DATABASE_NAME';
        export VUFORIA_TARGET_MANAGER_DATABASE_NAME=$MASTER_VUFORIA_TARGET_MANAGER_DATABASE_NAME;
        export VUFORIA_SERVER_ACCESS_KEY=$MASTER_VUFORIA_SERVER_ACCESS_KEY;
        export VUFORIA_SERVER_SECRET_KEY=$MASTER_VUFORIA_SERVER_SECRET_KEY;
       fi"

script:
    - "pytest --exitfirst -vvv --cov=src --cov=tests"

after_success:
    - "coveralls"
