language: "python"

python:
  - "3.5"

install:
  - "pip install --upgrade --editable .[dev]"

cache: "pip"

before_script:
    # Run linters
    - "flake8 ."
    - "prospector --strictness veryhigh"
    - "pylint src/vws"
    - "mypy src tests"
    # Make sure that imports are sorted as expected.
    - "isort --recursive --check-only"
    # Create an environment file used by `pytest-envfiles`.
    # We don't add to this because we have environment variables set in the CI
    # config.
    - "touch vuforia_secrets.env"

script:
    - "pytest --cov=src"

after_success:
    - "coveralls"
