sudo: false
language: python
python:
- '3.6'
addons:
  apt:
    packages:
    - enchant
before_install:
- travis_retry pip install --upgrade pip setuptools
install:
- travis_retry pip install --upgrade --editable .[dev]
cache: pip
script:
- make lint
- pytest -vvv --exitfirst tests/vws --cov src --cov tests
after_success:
- codecov
