# This makes Travis CI use the container-based infrastructure which starts
# tests faster.
sudo: false

language: "python"

python:
  - "3.6"

env:
  # Travis has a maximum test run time of 70 minutes.
  # In order to avoid this and to see failures faster, we run multiple builds
  # per commit.
  matrix:
      - "TEST_FILENAME=test_add_target.py"
      - "TEST_FILENAME=test_database_summary.py"
      - "TEST_FILENAME=test_delete_target.py"
      - "TEST_FILENAME=test_get_duplicates.py"
      - "TEST_FILENAME=test_get_target.py"
      - "TEST_FILENAME=test_invalid_given_id.py"
      - "TEST_FILENAME=test_invalid_json.py"
      - "TEST_FILENAME=test_query.py"
      - "TEST_FILENAME=test_target_list.py"
      - "TEST_FILENAME=test_target_summary.py"
      - "TEST_FILENAME=test_unexpected_headers.py"
      - "TEST_FILENAME=test_unexpected_json.py"
      - "TEST_FILENAME=test_update_target.py"
      - "TEST_FILENAME=test_usage.py"

addons:
  apt:
    packages:
        - "enchant"

before_install:
    - "travis_retry pip install --upgrade pip setuptools"

install:
  - "travis_retry pip install --upgrade --editable .[dev]"
  - "travis_retry npm install -g markdownlint-cli"

cache: "pip"

before_script:
    - "make lint"
    - "markdownlint --config .markdownlint.json README.md CONTRIBUTING.md"
    # Create an environment file used by `pytest-envfiles`.
    # We don't add to this because we have environment variables set in the CI
    # config.
    - "touch vuforia_secrets.env"
    # We use a different database for `master` builds.
    - "if [ \"$TRAVIS_BRANCH\" = \"master\" -a \"$TRAVIS_PULL_REQUEST\" = \"false\" ]; then
        echo 'Using Vuforia credentials for $MASTER_VUFORIA_TARGET_MANAGER_DATABASE_NAME';
        export VUFORIA_TARGET_MANAGER_DATABASE_NAME=$MASTER_VUFORIA_TARGET_MANAGER_DATABASE_NAME;
        export VUFORIA_SERVER_ACCESS_KEY=$MASTER_VUFORIA_SERVER_ACCESS_KEY;
        export VUFORIA_SERVER_SECRET_KEY=$MASTER_VUFORIA_SERVER_SECRET_KEY;
        export VUFORIA_CLIENT_ACCESS_KEY=$MASTER_VUFORIA_CLIENT_ACCESS_KEY;
        export VUFORIA_CLIENT_SECRET_KEY=$MASTER_VUFORIA_CLIENT_SECRET_KEY;
       fi"

script:
    - 'pytest --exitfirst -vvv tests/mock_vws/"$TEST_FILENAME" --cov=src --cov=tests'

after_success:
    - "codecov"
