sudo: false
language: python
python:
- '3.6'
env:
  matrix:
  - TEST_FILENAME=test_add_target.py
  - TEST_FILENAME=test_database_summary.py
  - TEST_FILENAME=test_delete_target.py
  - TEST_FILENAME=test_get_duplicates.py
  - TEST_FILENAME=test_get_target.py
  - TEST_FILENAME=test_invalid_given_id.py
  - TEST_FILENAME=test_invalid_json.py
  - TEST_FILENAME=test_query.py
  - TEST_FILENAME=test_target_list.py
  - TEST_FILENAME=test_target_summary.py
  - TEST_FILENAME=test_unexpected_headers.py
  - TEST_FILENAME=test_unexpected_json.py
  - TEST_FILENAME=test_update_target.py
  - TEST_FILENAME=test_usage.py
before_install:
- openssl aes-256-cbc -K $encrypted_5c29411ed445_key -iv $encrypted_5c29411ed445_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
cache: pip
before_script:
- python ci/set_secrets_file.py
script:
- echo 1
after_success:
- codecov
