language: "python"

python:
  - "3.5"

install:
  - "pip install --upgrade --editable .[dev]"

cache: "pip"

before_script:
    - "flake8 ."
    - "prospector --strictnessl veryhigh"
    - "pylint src/vws"
    - "mypy src"

script:
    - "pytest --cov=src"

after_success:
    - "coveralls"
